import { all, fork, takeLatest, put, delay} from 'redux-saga/effects';
import axios from 'axios';

import {
  LOG_IN_SUCCESS, 
  LOG_IN_REQUEST, 
  LOG_IN_FAILURE, 
  LOG_OUT_SUCCESS, 
  LOG_OUT_REQUEST, 
  LOG_OUT_FAILURE,
  SIGN_UP_SUCCESS, 
  SIGN_UP_REQUEST, 
  SIGN_UP_FAILURE,
  FOLLOW_REQUEST,
  FOLLOW_SUCCESS,
  FOLLOW_FAILURE,
  UNFOLLOW_REQUEST,
  UNFOLLOW_SUCCESS,
  UNFOLLOW_FAILURE,
} from '../reducers/user';

// -------로그인---------
function logInAPI(data) {
  return axios.post('/api/login', data); 
}

//action 이 매개변수는, action.type하면 로그인 request가 나올거고 action.data하면 로그인 데이터가 있다.
function* logIn(action) {
  //요청이 항상 성공하는 것이 아니라 실패할 수도 있으니 실패한 상황도 try/catch문으로 만들어준다.
  try {
    console.log('saga login');
    //요청의 결과를 받다.
    //const result = yield call(logInAPI);
    yield delay(1000);
    // 🤯 서버 구현하기 전까지 delay 사용하는걸로
    yield put({
      type: LOG_IN_SUCCESS, //성공시
      data: action.data, //데이터를 받아온다.
    });
  } catch (err) {
    yield put({
      type: LOG_IN_FAILURE,
      error: err.response.data,
    })
  }  
}

// -------로그아웃---------
// 로그아웃은 매개변수 넣는 곳에 따로 필요한 데이터가 없다.

function logOutAPI() {
  return axios.post('/api/logOut'); 
}

function* logOut() {  
  try {
    // const result = yield call(logOutAPI);
    yield delay(1000);
    // 🤯 서버 구현하기 전까지 delay 사용하는걸로
    yield put({
      type: LOG_OUT_SUCCESS,
    });
  } catch (err) {
    yield put({
      type: LOG_OUT_FAILURE,
      error: err.response.data,
    })
  }  
}

// ------------------------------------------------

function signUpAPI() {
  return axios.post('/api/signUp'); 
}

function* signUp() {  
  try {
    // const result = yield call(signUpAPI);
    yield delay(1000);
    // 🤯 서버 구현하기 전까지 delay 사용하는걸로
    // throw new Error(''); throw를 하면 에러날 때 바로 밑에 put함수를 적용해주는 것이 아니라 catch(err)로 간다.
    yield put({
      type: SIGN_UP_SUCCESS,
    });
  } catch (err) {
    yield put({
      type: SIGN_UP_FAILURE,
      error: err.response.data,
    })
  }  
}

// ------------------------------------------------

function followAPI() {
  return axios.post('/api/follow'); 
}

function* follow(action) {  
  try {
    // const result = yield call(followAPI);
    yield delay(1000);
    // 🤯 서버 구현하기 전까지 delay 사용하는걸로
    // throw new Error(''); throw를 하면 에러날 때 바로 밑에 put함수를 적용해주는 것이 아니라 catch(err)로 간다.
    yield put({
      type: FOLLOW_SUCCESS,
      data: action.data,
    });
  } catch (err) {
    yield put({
      type: FOLLOW_FAILURE,
      error: err.response.data,
    })
  }  
}

// ------------------------------------------------

function unfollowAPI() {
  return axios.post('/api/unfollow'); 
}

function* unfollow(action) {  
  try {
    // const result = yield call(unfollowAPI);
    yield delay(1000);
    // 🤯 서버 구현하기 전까지 delay 사용하는걸로
    // throw new Error(''); throw를 하면 에러날 때 바로 밑에 put함수를 적용해주는 것이 아니라 catch(err)로 간다.
    yield put({
      type: UNFOLLOW_SUCCESS,
      data: action.data,
    });
  } catch (err) {
    yield put({
      type: UNFOLLOW_FAILURE,
      error: err.response.data,
    })
  }  
}

// ------------------------------------------------

function* watchFollow() {
  yield takeLatest(FOLLOW_REQUEST, follow);
}

function* watchUnfollow() {
  yield takeLatest(UNFOLLOW_REQUEST, unfollow);
}

//LOG_IN이란 액션이 실행되면 뒤에있는 logIn 제너레이터 함수가 실행되도록
function* watchLogIn() {
  yield takeLatest(LOG_IN_REQUEST, logIn);
}

function* watchLogOut() {
  yield takeLatest(LOG_OUT_REQUEST, logOut);
}

function* watchSignUp() {
  yield takeLatest(SIGN_UP_REQUEST, signUp);
}

export default function* userSaga() {
  yield all([
    fork(watchFollow),
    fork(watchUnfollow),
    fork(watchLogIn),
    fork(watchLogOut),
    fork(watchSignUp),
  ])
}